using System;
using System.Collections.Generic;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Build.Framework;
using Microsoft.Build.Utilities;

namespace SpecTask;

/// <summary>
/// Reads every spec once, before the compiler starts, and writes two things:
/// a C# file of [GeneratedRegex] partials, and a normalized model for the source generator.
/// </summary>
/// <remarks>
/// The patterns file has to come from here rather than from the generator, because only a file
/// MSBuild puts in @(Compile) is part of the compilation the regex source generator sees.
///
/// The normalized model is the reason this is not "parse the spec twice". The generator never
/// opens the yaml - it reads what this produced, which also means it needs no yaml parser and
/// none of the embedded-dependency machinery that would come with one.
/// </remarks>
public sealed class ExtractSpec : Task {
    [Required] public ITaskItem[] Specs { get; set; } = Array.Empty<ITaskItem>();
    [Required] public string PatternsFile { get; set; } = "";
    [Required] public string ModelFile { get; set; } = "";

    public override bool Execute() {
        var patterns = new Dictionary<string, string>(StringComparer.Ordinal);
        var model = new StringBuilder();

        foreach (var spec in Specs) {
            var path = spec.GetMetadata("FullPath");
            Log.LogMessage(MessageImportance.Normal, $"ExtractSpec reading {path}");

            foreach (var line in ParseSpec(File.ReadAllLines(path), patterns)) {
                model.AppendLine(line);
            }
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/> written by the ExtractSpec MSBuild task");
        source.AppendLine("using System.Text.RegularExpressions;");
        source.AppendLine();
        source.AppendLine("namespace Spec.Generated;");
        source.AppendLine();
        source.AppendLine("public static partial class SpecPatterns {");
        foreach (var entry in patterns) {
            source.AppendLine($"    [GeneratedRegex(@\"{entry.Value.Replace("\"", "\"\"")}\")]");
            source.AppendLine($"    public static partial Regex {entry.Key}();");
            source.AppendLine();
        }
        source.AppendLine("}");

        WriteIfDifferent(PatternsFile, source.ToString());
        WriteIfDifferent(ModelFile, model.ToString());

        return !Log.HasLoggedErrors;
    }

    /// <summary>
    /// A deliberately small stand-in for a real OpenAPI reader. The mechanism under test is the
    /// hand-off, not the parsing - a real task would use the same reader the generator uses today.
    /// </summary>
    private static IEnumerable<string> ParseSpec(string[] lines, Dictionary<string, string> patterns) {
        string? type = null;
        string? property = null;

        foreach (var raw in lines) {
            var line = raw.TrimEnd();
            if (line.Length == 0 || line.TrimStart().StartsWith("#")) continue;

            var indent = line.Length - line.TrimStart().Length;
            var text = line.Trim();

            if (indent == 0 && text.EndsWith(":")) {
                type = text.TrimEnd(':');
                yield return $"type|{type}";
            } else if (indent == 2 && text.EndsWith(":")) {
                property = text.TrimEnd(':');
            } else if (indent == 4 && type != null && property != null) {
                var split = text.IndexOf(':');
                var key = text.Substring(0, split).Trim();
                var value = text.Substring(split + 1).Trim().Trim('"');

                if (key == "pattern") {
                    // The task names the member and tells the generator what it is, so the two
                    // never have to agree on a naming convention independently.
                    var member = "P_" + Hash(value);
                    patterns[member] = value;
                    yield return $"prop|{property}|pattern|{member}";
                } else if (key == "required" && value == "true") {
                    yield return $"prop|{property}|required|";
                }
            }
        }
    }

    private static string Hash(string value) {
        using var sha = SHA256.Create();
        var bytes = sha.ComputeHash(Encoding.UTF8.GetBytes(value));
        var builder = new StringBuilder();
        for (var i = 0; i < 6; i++) builder.Append(bytes[i].ToString("x2"));
        return builder.ToString();
    }

    private static void WriteIfDifferent(string path, string content) {
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        if (File.Exists(path) && File.ReadAllText(path) == content) return;
        File.WriteAllText(path, content);
    }
}
