using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SpecGen;

/// <summary>
/// Emits a validator per spec type, from the normalized model the ExtractSpec task wrote.
/// </summary>
/// <remarks>
/// Note what is absent: any yaml parser, and therefore any embedded dependency, AssemblyResolve
/// hook or RS1035 suppression. The spec was read once, before the compiler started.
/// </remarks>
[Generator]
public sealed class ValidatorGenerator : IIncrementalGenerator {

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var model = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith("spec-model.txt", System.StringComparison.OrdinalIgnoreCase))
            .Select(static (text, ct) => text.GetText(ct)?.ToString() ?? "")
            .Collect();

        context.RegisterSourceOutput(model, static (production, texts) => {
            foreach (var text in texts) {
                Emit(production, text);
            }
        });
    }

    private static void Emit(SourceProductionContext production, string model) {
        string? type = null;
        var body = new StringBuilder();

        foreach (var line in model.Split('\n').Select(l => l.Trim()).Where(l => l.Length > 0)) {
            var parts = line.Split('|');

            if (parts[0] == "type") {
                if (type != null) Flush(production, type, body);
                type = parts[1];
                body.Clear();
                continue;
            }

            var property = parts[1];
            var field = char.ToLowerInvariant(property[0]) + property.Substring(1);

            if (parts[2] == "required") {
                body.AppendLine($"        if (string.IsNullOrWhiteSpace(value.{property})) errors.Add(\"{field}: required\");");
            } else if (parts[2] == "pattern") {
                // Calls the partial the task wrote. The regex source generator implemented it,
                // because that file reached the compiler as an ordinary source file.
                body.AppendLine($"        if (value.{property} is not null && !global::Spec.Generated.SpecPatterns.{parts[3]}().IsMatch(value.{property})) errors.Add(\"{field}: pattern\");");
            }
        }

        if (type != null) Flush(production, type, body);
    }

    private static void Flush(SourceProductionContext production, string type, StringBuilder body) {
        var source = $$"""
            // <auto-generated/> written by the ValidatorGenerator source generator
            using System.Collections.Generic;

            namespace Spec.Generated;

            public static class {{type}}Validator {
                public static IReadOnlyList<string> Validate({{type}} value) {
                    var errors = new List<string>();
            {{body.ToString().TrimEnd()}}
                    return errors;
                }
            }
            """;

        production.AddSource($"{type}Validator.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
