using CSharpAuthor;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// How every emitter in this package turns a <see cref="CSharpFileDefinition"/> into text, and the
/// small vocabulary they share for naming types the IR carries as strings.
/// </summary>
/// <remarks>
/// <para>
/// One place rather than three, because the settings are the contract: global-qualified type
/// references so nothing emitted can collide with a name in the consumer's compilation, K&amp;R
/// braces and four-space indents to match §13, and <c>\n</c> line endings so the same model emits
/// the same bytes on every machine.
/// </para>
/// <para>
/// The IR deliberately carries types as strings - fully qualified, rendered by the front ends with
/// <c>SymbolDisplayFormat.FullyQualifiedFormat</c> - so the emitters cannot hold Roslyn symbols
/// across an incremental-generator boundary. <see cref="TypeRef"/> is the bridge back: it turns
/// one of those strings into an <see cref="ITypeDefinition"/> at the emitter's edge, so every
/// declaration that mentions the type goes through CSharpAuthor's type model rather than through
/// string concatenation.
/// </para>
/// </remarks>
internal static class EmitterOutput {

    /// <summary>
    /// A generated file: auto-generated header, <c>#nullable enable</c>, and a file-scoped
    /// namespace when there is a namespace to declare.
    /// </summary>
    public static CSharpFileDefinition GeneratedFile(string ns) {
        var file = new CSharpFileDefinition(ns);

        if (ns.Length > 0) {
            file.FileScopedNamespace = true;
        }

        Header(file);

        return file;
    }

    /// <summary>
    /// The header every generated file carries. Split out for the one file that cannot go through
    /// <see cref="GeneratedFile"/> because it declares two namespaces.
    /// </summary>
    public static void Header(CSharpFileDefinition file) {
        file.AddAutoGeneratedHeader();

        // Enable only, no trailing restore: the directive governs a whole generated file, and
        // nothing follows it that the restore could protect.
        file.AddLeadingTrait(new NullableEnableComponent(true));
    }

    /// <summary>Serializes a file with this package's output settings.</summary>
    public static string Render(CSharpFileDefinition file) {
        var context = new OutputContext(new OutputContextOptions {
            TypeOutputMode = TypeOutputMode.Global,
            BraceStyle = BraceStyle.KAndR,

            // Registrations and Regex constructions read better as the one line a person would
            // have written; nothing this package emits carries an argument list long enough to
            // want breaking.
            BreakInvokeLines = false,
        });

        file.WriteOutput(context);

        return context.Output();
    }

    /// <summary>
    /// An IR type string - <c>global::Sample.Pet</c> - as a type reference.
    /// </summary>
    /// <remarks>
    /// The front ends qualify with <c>SymbolDisplayFormat.FullyQualifiedFormat</c> over closed,
    /// non-generic named types - generic models are refused outright (VM0079) and nullable nested
    /// targets are unwrapped before they are named - so the string is always <c>global::</c> plus
    /// dotted identifiers. Anything else is a front-end defect, and throwing here surfaces it at
    /// generation time instead of compiling it into the consumer's build as CS0246.
    /// </remarks>
    public static ITypeDefinition TypeRef(string qualifiedName) {
        const string prefix = "global::";

        var name = qualifiedName.StartsWith(prefix, StringComparison.Ordinal)
            ? qualifiedName.Substring(prefix.Length)
            : qualifiedName;

        if (name.Length == 0 || name.IndexOfAny(UnexpectedInATypeName) >= 0) {
            throw new ArgumentException(
                $"'{qualifiedName}' is not a fully qualified non-generic type name; the front end that produced it is broken.",
                nameof(qualifiedName));
        }

        var dot = name.LastIndexOf('.');

        return dot < 0
            ? NamedType(string.Empty, name)
            : TypeDefinition.Get(name.Substring(0, dot), name.Substring(dot + 1));
    }

    /// <summary>
    /// A type by namespace and name, with the global namespace actually reachable.
    /// </summary>
    /// <remarks>
    /// <see cref="TypeDefinition.Get(string, string, bool, bool)"/> writes an empty-namespace type
    /// as its bare name in every mode, because the predefined keyword types carry an empty
    /// namespace and <c>global::int</c> would not compile. A user type in the global namespace is
    /// the case that distinction drops: bare <c>Pet</c> inside the emitted
    /// <c>Microsoft.Extensions.DependencyInjection</c> block resolves through every enclosing
    /// namespace before the global one, so anything named <c>Pet</c> along that walk captures it -
    /// the exact failure mode Global output exists to remove. Until CSharpAuthor can say
    /// <c>global::Pet</c> itself, <see cref="GlobalNamespaceType"/> says it here.
    /// </remarks>
    public static ITypeDefinition NamedType(string ns, string name) =>
        ns.Length == 0 ? new GlobalNamespaceType(name) : TypeDefinition.Get(ns, name);

    private static readonly char[] UnexpectedInATypeName = { '<', '>', '[', ']', '?', ' ', ',' };

    /// <summary>
    /// A non-generic type declared in the global namespace, written <c>global::Name</c> in every
    /// mode - the one spelling C# accepts for it from inside any other namespace, and legal
    /// everywhere else too.
    /// </summary>
    private sealed class GlobalNamespaceType : ITypeDefinition {
        private readonly string _name;
        private readonly bool _nullable;

        public GlobalNamespaceType(string name, bool nullable = false) {
            _name = name;
            _nullable = nullable;
        }

        public TypeDefinitionEnum TypeDefinitionEnum => TypeDefinitionEnum.ClassDefinition;

        public bool IsNullable => _nullable;

        public bool IsArray => false;

        public IReadOnlyList<bool> NullableAnnotations => new[] { _nullable };

        public IReadOnlyList<int> ArrayRanks => Array.Empty<int>();

        public string Name => _name;

        public string Namespace => string.Empty;

        public ITypeDefinition? ContainingType => null;

        public IEnumerable<string> KnownNamespaces => Array.Empty<string>();

        public IReadOnlyList<ITypeDefinition> TypeArguments => Array.Empty<ITypeDefinition>();

        public void WriteTypeName(
            System.Text.StringBuilder builder, TypeOutputMode typeOutputMode = TypeOutputMode.ShortName) {
            builder.Append("global::");
            builder.Append(_name);

            if (_nullable) {
                builder.Append('?');
            }
        }

        public ITypeDefinition MakeNullable(bool nullable = true) => new GlobalNamespaceType(_name, nullable);

        public ITypeDefinition MakeArray() => MakeArray(1);

        // Nothing the emitters produce needs an array of a global-namespace type - element arrays
        // are arrays of IValidatorFor<T>, which carries its namespace. Refused loudly rather than
        // written bare, which is the silent capture this class exists to remove.
        public ITypeDefinition MakeArray(int rank) =>
            throw new NotSupportedException(
                $"An array of the global-namespace type '{_name}' has no writer; " +
                "widen GlobalNamespaceType if an emitter ever needs one.");

        public int CompareTo(ITypeDefinition other) =>
            other is null ? 1 : string.CompareOrdinal(_name, other.Namespace.Length == 0 ? other.Name : $"{other.Namespace}.{other.Name}");
    }

    /// <summary><c>IValidatorFor&lt;T&gt;</c> closed over <paramref name="validated"/>.</summary>
    public static ITypeDefinition ValidatorFor(ITypeDefinition validated) =>
        new GenericTypeDefinition(
            TypeDefinitionEnum.InterfaceDefinition, "ValidationModules", "IValidatorFor", new[] { validated });

    /// <summary><c>IEnumerable&lt;T&gt;</c> closed over <paramref name="element"/>.</summary>
    public static ITypeDefinition EnumerableOf(ITypeDefinition element) =>
        new GenericTypeDefinition(
            TypeDefinitionEnum.InterfaceDefinition, "System.Collections.Generic", "IEnumerable", new[] { element });

    /// <summary>
    /// A blank separator line. <see cref="BaseBlockDefinition.NewLine"/> writes the block's indent
    /// before the break, which leaves trailing whitespace on an empty line; this writes the break
    /// alone.
    /// </summary>
    public static void BlankLine(BaseBlockDefinition block) =>
        block.Add(new CodeOutputComponent("\n") { Indented = false });

    /// <summary>
    /// A bare sequence of statements, for building a method body before the method exists.
    /// </summary>
    /// <remarks>
    /// <see cref="ValidatorEmitter"/> walks the properties once, and the walk both produces the
    /// body's statements and discovers what has to precede them - the hoisted condition locals,
    /// evaluated once per pass before any test runs. The statements land here, the method is
    /// assembled afterwards, and <see cref="BaseBlockDefinition.Add{T}"/> splices the buffer in
    /// whole. It writes at whatever indent is current when the enclosing block writes it, which is
    /// the same contract a <c>switch</c> arm's statement list already relies on.
    /// </remarks>
    public sealed class StatementBuffer : BaseBlockDefinition {

        protected override void WriteComponentOutput(IOutputContext outputContext) {
            foreach (var statement in StatementList) {
                statement.WriteOutput(outputContext);
            }
        }
    }
}
