using CSharpAuthor;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// How every emitter in this package turns a <see cref="CSharpFileDefinition"/> into text, and the
/// small vocabulary they share for naming types the IR carries as strings.
/// </summary>
/// <remarks>
/// <para>
/// One place rather than three, because the settings are the contract: global-qualified type
/// references so nothing emitted can collide with a name in the consumer's compilation, K&amp;R
/// braces and four-space indents to match §13, and <c>\n</c> line endings so the same model emits
/// the same bytes on every machine.
/// </para>
/// <para>
/// The IR deliberately carries types as strings - fully qualified, rendered by the front ends with
/// <c>SymbolDisplayFormat.FullyQualifiedFormat</c> - so the emitters cannot hold Roslyn symbols
/// across an incremental-generator boundary. <see cref="TypeRef"/> is the bridge back: it turns
/// one of those strings into an <see cref="ITypeDefinition"/> at the emitter's edge, so every
/// declaration that mentions the type goes through CSharpAuthor's type model rather than through
/// string concatenation.
/// </para>
/// </remarks>
internal static class EmitterOutput {

    /// <summary>
    /// A generated file: auto-generated header, <c>#nullable enable</c>, and a file-scoped
    /// namespace when there is a namespace to declare.
    /// </summary>
    public static CSharpFileDefinition GeneratedFile(string ns) {
        var file = new CSharpFileDefinition(ns);

        if (ns.Length > 0) {
            file.FileScopedNamespace = true;
        }

        Header(file);

        return file;
    }

    /// <summary>
    /// The header every generated file carries. Split out for the one file that cannot go through
    /// <see cref="GeneratedFile"/> because it declares two namespaces.
    /// </summary>
    public static void Header(CSharpFileDefinition file) {
        file.AddAutoGeneratedHeader();

        // Enable only, no trailing restore: the directive governs a whole generated file, and
        // nothing follows it that the restore could protect.
        file.AddLeadingTrait(new NullableEnableComponent(true));
    }

    /// <summary>
    /// Serializes a file with this package's output settings. The brace style is the caller's,
    /// resolved from the <c>GeneratedCodeStyle</c> build property; everything else is fixed.
    /// </summary>
    public static string Render(CSharpFileDefinition file, BraceStyle style) {
        var context = new OutputContext(new OutputContextOptions {
            TypeOutputMode = TypeOutputMode.Global,
            BraceStyle = style,

            // Registrations and Regex constructions read better as the one line a person would
            // have written; nothing this package emits carries an argument list long enough to
            // want breaking.
            BreakInvokeLines = false,
        });

        file.WriteOutput(context);

        return context.Output();
    }

    /// <summary>
    /// An IR type string - <c>global::Sample.Pet</c> - as a type reference.
    /// </summary>
    /// <remarks>
    /// The front ends qualify with <c>SymbolDisplayFormat.FullyQualifiedFormat</c> over closed,
    /// non-generic named types - generic models are refused outright (VM0079) and nullable nested
    /// targets are unwrapped before they are named - so the string is always <c>global::</c> plus
    /// dotted identifiers. Anything else is a front-end defect, and throwing here surfaces it at
    /// generation time instead of compiling it into the consumer's build as CS0246.
    /// </remarks>
    public static ITypeDefinition TypeRef(string qualifiedName) {
        const string prefix = "global::";

        var name = qualifiedName.StartsWith(prefix, StringComparison.Ordinal)
            ? qualifiedName.Substring(prefix.Length)
            : qualifiedName;

        if (name.Length == 0 || name.IndexOfAny(UnexpectedInATypeName) >= 0) {
            throw new ArgumentException(
                $"'{qualifiedName}' is not a fully qualified non-generic type name; the front end that produced it is broken.",
                nameof(qualifiedName));
        }

        var dot = name.LastIndexOf('.');

        return dot < 0
            ? NamedType(string.Empty, name)
            : TypeDefinition.Get(name.Substring(0, dot), name.Substring(dot + 1));
    }

    /// <summary>
    /// A type by namespace and name, the global namespace included.
    /// </summary>
    /// <remarks>
    /// This used to route an empty namespace through a local <c>GlobalNamespaceType</c> that wrote
    /// <c>global::Pet</c> itself, because CSharpAuthor wrote every empty-namespace type bare - the
    /// predefined keyword types share that shape, and <c>global::int</c> would not compile. The
    /// distinction was upstreamed as predicted: from 2.0.0-preview1005, Global mode qualifies an
    /// empty-namespace user type and leaves the keywords bare (its migration note B13), so
    /// <see cref="TypeDefinition.Get(string, string, bool, bool)"/> is the whole answer.
    /// </remarks>
    public static ITypeDefinition NamedType(string ns, string name) =>
        TypeDefinition.Get(ns, name);

    private static readonly char[] UnexpectedInATypeName = { '<', '>', '[', ']', '?', ' ', ',' };

    /// <summary><c>IValidatorFor&lt;T&gt;</c> closed over <paramref name="validated"/>.</summary>
    public static ITypeDefinition ValidatorFor(ITypeDefinition validated) =>
        new GenericTypeDefinition(
            TypeDefinitionEnum.InterfaceDefinition, "ValidationModules", "IValidatorFor", new[] { validated });

    /// <summary><c>IEnumerable&lt;T&gt;</c> closed over <paramref name="element"/>.</summary>
    public static ITypeDefinition EnumerableOf(ITypeDefinition element) =>
        new GenericTypeDefinition(
            TypeDefinitionEnum.InterfaceDefinition, "System.Collections.Generic", "IEnumerable", new[] { element });

    /// <summary>
    /// The runtime namer class for a <c>ValidationModules_FieldNaming</c> value. Shared by the
    /// registration emitter, which registers it as the default, and the validator emitter, which
    /// hands the same instance to the DataAnnotations bridge - one mapping, so a member name
    /// resolved at run time lands on the same path a compiled literal would have.
    /// </summary>
    public static string NamerFor(string? fieldNamer) => fieldNamer switch {
        "PascalCase" or "AsDeclared" => "PascalCaseFieldNamer",
        "SnakeCase" => "SnakeCaseFieldNamer",
        _ => "CamelCaseFieldNamer",
    };

    /// <summary>The namer's singleton, spelled the way generated code says it.</summary>
    public static string NamerInstance(string? fieldNamer) =>
        $"global::ValidationModules.Naming.{NamerFor(fieldNamer)}.Instance";

    /// <summary>
    /// A blank separator line. <see cref="BaseBlockDefinition.NewLine"/> writes the block's indent
    /// before the break, which leaves trailing whitespace on an empty line; this writes the break
    /// alone.
    /// </summary>
    public static void BlankLine(BaseBlockDefinition block) =>
        block.Add(new CodeOutputComponent("\n") { Indented = false });

    /// <summary>
    /// A bare sequence of statements, for building a method body before the method exists.
    /// </summary>
    /// <remarks>
    /// <see cref="ValidatorEmitter"/> walks the properties once, and the walk both produces the
    /// body's statements and discovers what has to precede them - the hoisted condition locals,
    /// evaluated once per pass before any test runs. The statements land here, the method is
    /// assembled afterwards, and <see cref="BaseBlockDefinition.Add{T}"/> splices the buffer in
    /// whole. It writes at whatever indent is current when the enclosing block writes it, which is
    /// the same contract a <c>switch</c> arm's statement list already relies on.
    /// </remarks>
    public sealed class StatementBuffer : BaseBlockDefinition {

        protected override void WriteComponentOutput(IOutputContext outputContext) {
            foreach (var statement in StatementList) {
                statement.WriteOutput(outputContext);
            }
        }
    }
}
