using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using ValidationModules.SourceGenerator.Impl.FrontEnds;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// Lifts a rules class's <c>Ensure</c> predicates into static methods the validator can call.
/// </summary>
/// <remarks>
/// <para>
/// <b>Why lift rather than inline.</b> A predicate's source resolves against the using directives of
/// the file that declared it - <c>x =&gt; x.Status == Status.Active</c> needs the <c>using</c> that
/// was in the author's file - and the validator is emitted into a different file that does not have
/// them. The alternatives were a symbol-qualifying rewriter, which has to reduce extension-method
/// invocations to their static form to be correct, or this: emit one file per rules class carrying
/// that file's own usings, and call into it. The call costs nothing an inliner will not remove, and
/// the predicate stays readable in <c>obj/…/generated</c>, which HANDOFF.md §3.5 leans on.
/// </para>
/// <para>
/// This is also the honest account of what <c>Ensure</c> is: sugar over <c>Apply</c>, where the
/// generator writes the static method the author would otherwise have written by hand.
/// </para>
/// <para>
/// The one Roslyn-coupled emitter, because it copies syntax. The others take only the IR, which is
/// what lets an MSBuild task drive them (plan §9).
/// </para>
/// </remarks>
public sealed class PredicateEmitter {

    /// <summary>The class name predicates from <paramref name="rulesClass"/> are lifted into.</summary>
    public static string ContainerFor(INamedTypeSymbol rulesClass) => $"{rulesClass.Name}_Rules";

    /// <summary>Emits the container, or null when the rules class declared no predicates.</summary>
    public string? Emit(RulesDeclaration declaration) {
        if (declaration.Predicates.Count == 0) {
            return null;
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // The declaring file's usings, copied verbatim. This is the whole reason the file exists;
        // without them a predicate naming any type by its short name fails to compile, in generated
        // code, which plan §7.5 calls the worst possible place for an error to land.
        foreach (var directive in UsingsOf(declaration.RulesClass)) {
            builder.AppendLine(directive);
        }

        builder.AppendLine();

        var ns = declaration.RulesClass.ContainingNamespace;

        if (!ns.IsGlobalNamespace) {
            builder.AppendLine($"namespace {ns.ToDisplayString()};");
            builder.AppendLine();
        }

        var target = declaration.Target.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        builder.AppendLine("/// <summary>");
        builder.AppendLine($"/// The Ensure predicates of {declaration.RulesClass.Name}, as static methods.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"internal static class {ContainerFor(declaration.RulesClass)} {{");

        foreach (var predicate in declaration.Predicates) {
            var parameter = ParameterOf(predicate.Lambda) ?? "value";
            var body = predicate.Body;

            builder.AppendLine();
            builder.AppendLine($"    public static bool {predicate.MethodName}({target} {parameter}) =>");
            builder.AppendLine($"        {body};");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// Every using directive in scope at the rules class, innermost namespace outwards.
    /// </summary>
    private static IEnumerable<string> UsingsOf(INamedTypeSymbol rulesClass) {
        var seen = new HashSet<string>(StringComparer.Ordinal);

        foreach (var reference in rulesClass.DeclaringSyntaxReferences) {
            var node = reference.GetSyntax();

            for (var current = node; current is not null; current = current.Parent) {
                var directives = current switch {
                    BaseNamespaceDeclarationSyntax declaration => declaration.Usings,
                    CompilationUnitSyntax unit => unit.Usings,
                    _ => default,
                };

                foreach (var directive in directives) {
                    var text = directive.ToString();

                    if (seen.Add(text)) {
                        yield return text;
                    }
                }
            }
        }
    }

    private static string? ParameterOf(ExpressionSyntax lambda) => lambda switch {
        SimpleLambdaExpressionSyntax simple => simple.Parameter.Identifier.Text,
        ParenthesizedLambdaExpressionSyntax parenthesized when parenthesized.ParameterList.Parameters.Count == 1
            => parenthesized.ParameterList.Parameters[0].Identifier.Text,
        _ => null,
    };

}
