using System.Text;
using ValidationModules.SourceGenerator.Impl.Models;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// Emits the registration for an assembly's validators, in whichever shape the consumer's
/// references call for.
/// </summary>
/// <remarks>
/// <para>
/// <b>One body, two wrappers</b>, which is what plan §7.3 asks for. The body is an
/// <c>IServiceCollection</c> extension - <c>services.AddMyAppValidators()</c> - and when
/// DependencyModules is referenced the emitted module is a one-line call to it rather than a second
/// copy of the same registrations. Before this, the two branches shared an emitter and produced
/// genuinely different bodies: a table of <c>ValidatorRegistration</c> records on one side and
/// direct <c>AddSingleton</c> calls on the other.
/// </para>
/// <para>
/// <b>Why the extension rather than the table.</b> The table erased the generic - a
/// <c>Type</c> beside a <c>Func&lt;IServiceProvider, object&gt;</c>, so nothing checked that the
/// factory for <c>typeof(IValidatorFor&lt;Pet&gt;)</c> returned one - allocated an array of
/// closures at static init only to iterate it once at startup, and lived in a class the consumer
/// had to already know the name of, in a namespace derived from the sanitized assembly name.
/// <c>ValidatorRegistration</c> and <c>AddValidationModules(IReadOnlyList&lt;…&gt;)</c> remain in the
/// runtime for anyone hand-building a table; nothing generates one.
/// </para>
/// <para>
/// <b>The method name carries the assembly, and has to.</b> Each assembly registers its own
/// validators - there is deliberately no cross-assembly scanning - so two of them emitting
/// <c>AddValidationModules()</c> on <c>IServiceCollection</c> would be CS0121 at the composition
/// root. <c>AddMyAppValidators()</c> and <c>AddMyLibValidators()</c> compose without ceremony.
/// </para>
/// </remarks>
public sealed class RegistrationEmitter {

    /// <param name="models">The validated types, already ordered.</param>
    /// <param name="mode">Which wrapper to emit around the shared body.</param>
    /// <param name="assemblyNamespace">The sanitized assembly name, which names the method.</param>
    /// <param name="fieldNamer">
    /// The naming policy the validators were emitted with. Registered as the default
    /// <see cref="ValidationModules.Naming.IValidationFieldNamer"/> so that the engines which
    /// resolve one at run time agree with the literals baked into the generated code.
    /// </param>
    public string? Emit(
        IReadOnlyList<ValidatedTypeModel> models,
        RegistrationMode mode,
        string assemblyNamespace,
        string? fieldNamer = null) {

        if (models.Count == 0 || mode == RegistrationMode.None) {
            return null;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        // Block-scoped, because the extension belongs in the DI namespace by convention and the
        // module belongs beside the consumer's own types, and both land in this one file.
        EmitExtension(builder, models, assemblyNamespace, fieldNamer);

        if (mode == RegistrationMode.DependencyModules) {
            builder.AppendLine();
            EmitModule(builder, assemblyNamespace);
        }

        return builder.ToString();
    }

    private static void EmitExtension(
        StringBuilder builder, IReadOnlyList<ValidatedTypeModel> models, string ns, string? fieldNamer) {

        builder.AppendLine("namespace Microsoft.Extensions.DependencyInjection {");
        builder.AppendLine("    using global::Microsoft.Extensions.DependencyInjection.Extensions;");
        builder.AppendLine("    using global::ValidationModules;");
        builder.AppendLine("    using global::ValidationModules.Naming;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Registers every validator this assembly generated.</summary>");
        builder.AppendLine($"    public static class {Identifier(ns)}ValidationExtensions {{");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>");
        builder.AppendLine("        /// Adds this assembly's generated validators, and a validation runner for each");
        builder.AppendLine("        /// validated type.");
        builder.AppendLine("        /// </summary>");
        builder.AppendLine("        /// <remarks>");
        builder.AppendLine("        /// <b>Not idempotent.</b> Calling this twice registers every validator twice, and a");
        builder.AppendLine("        /// runner merges every registered validator for a type - so each error would be");
        builder.AppendLine("        /// reported twice. Add rather than TryAdd is deliberate: registering a second");
        builder.AppendLine("        /// validator for one type is how a hand-written rule composes with the generated");
        builder.AppendLine("        /// one, so this cannot dedupe without breaking that.");
        builder.AppendLine("        /// </remarks>");
        builder.AppendLine($"        public static IServiceCollection Add{Identifier(ns)}Validators(this IServiceCollection services) {{");

        foreach (var model in models) {
            // The container constructs it and owns its lifetime, and injects whatever validates
            // each nested type. Closed generics, so the trimmer keeps the constructor and nothing
            // resolves reflectively at run time.
            builder.AppendLine(
                $"            services.AddSingleton<IValidatorFor<{model.QualifiedTypeName}>, {Qualified(model)}>();");
        }

        builder.AppendLine();

        // Closed per type rather than an open generic: AddScoped(typeof(ValidationRunner<>)) would
        // have MS.DI construct it reflectively, which a Native AOT publish cannot do.
        foreach (var model in models) {
            builder.AppendLine($"            services.AddValidationRunner<{model.QualifiedTypeName}>();");
        }

        builder.AppendLine();
        builder.AppendLine("            // TryAdd, so a namer the consumer registered first survives. The policy here is");
        builder.AppendLine("            // the one the literals above were emitted with, so the engines that resolve a");
        builder.AppendLine("            // namer at run time agree with the generated code by default.");
        builder.AppendLine(
            $"            services.TryAddSingleton<IValidationFieldNamer>({NamerFor(fieldNamer)}.Instance);");
        builder.AppendLine();
        builder.AppendLine("            return services;");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    /// <summary>
    /// The DependencyModules wrapper: one call into the body above.
    /// </summary>
    /// <remarks>
    /// Emitted whole rather than as a partial for DM's own generator to complete, because generators
    /// cannot see each other's output - an attribute this one wrote would never reach DM's.
    /// <c>IDependencyModule</c> has exactly one member without a default implementation, so there is
    /// nothing left to complete.
    /// </remarks>
    private static void EmitModule(StringBuilder builder, string ns) {
        builder.AppendLine($"namespace {ns} {{");
        builder.AppendLine("    using global::DependencyModules.Runtime.Interfaces;");
        builder.AppendLine("    using global::Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Registers every validator this assembly generated.</summary>");
        builder.AppendLine("    public sealed class ValidationModule : IDependencyModule {");
        builder.AppendLine("        public void PopulateServiceCollection(IServiceCollection services) =>");
        builder.AppendLine($"            services.Add{Identifier(ns)}Validators();");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    /// <summary>
    /// The sanitized assembly name as a single identifier: "My.App" names AddMyAppValidators.
    /// </summary>
    /// <remarks>
    /// The namespace is already sanitized to valid identifier characters, so only the separators
    /// need removing. Never empty - an assembly with no usable name resolves to "Generated".
    /// </remarks>
    private static string Identifier(string ns) => ns.Replace(".", string.Empty);

    private static string NamerFor(string? fieldNamer) => fieldNamer switch {
        "PascalCase" or "AsDeclared" => "PascalCaseFieldNamer",
        "SnakeCase" => "SnakeCaseFieldNamer",
        _ => "CamelCaseFieldNamer",
    };

    private static string Qualified(ValidatedTypeModel model) =>
        model.Namespace.Length == 0
            ? $"global::{model.ValidatorName}"
            : $"global::{model.Namespace}.{model.ValidatorName}";

    // Kept deliberately: registering by implementation type is what lets the container inject the
    // nested sets. A factory returning a hand-built instance would pin the graph at generation
    // time and defeat the point.
}
