using System.Text;
using ValidationModules.SourceGenerator.Impl.Models;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// Emits the registration for an assembly's validators, in whichever shape the consumer's
/// references call for.
/// </summary>
/// <remarks>
/// <para>
/// Two branches sharing one body, per plan §7.3. When DependencyModules is referenced the
/// validators land in a complete <c>IDependencyModule</c>; otherwise they land in a static table
/// that <c>AddValidationModules</c> consumes. Only the wrapper differs.
/// </para>
/// <para>
/// The module is emitted whole rather than as a partial completed by DependencyModules' own
/// generator, because generators cannot see each other's output - an attribute this generator wrote
/// would never reach DM's. <c>IDependencyModule</c> has exactly one member without a default
/// implementation, so there is nothing to complete.
/// </para>
/// </remarks>
public sealed class RegistrationEmitter {

    public string? Emit(IReadOnlyList<ValidatedTypeModel> models, RegistrationMode mode, string assemblyNamespace) {
        if (models.Count == 0 || mode == RegistrationMode.None) {
            return null;
        }

        return mode == RegistrationMode.DependencyModules
            ? EmitModule(models, assemblyNamespace)
            : EmitTable(models, assemblyNamespace);
    }

    private static string EmitModule(IReadOnlyList<ValidatedTypeModel> models, string ns) {
        var builder = Header(ns);

        builder.AppendLine("using DependencyModules.Runtime.Interfaces;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine("using ValidationModules;");
        builder.AppendLine();
        if (ns.Length > 0) {
            builder.AppendLine($"namespace {ns};");
            builder.AppendLine();
        }

        builder.AppendLine("/// <summary>Registers every validator this assembly generated.</summary>");
        builder.AppendLine("public sealed class ValidationModule : IDependencyModule {");
        builder.AppendLine("    public void PopulateServiceCollection(IServiceCollection services) {");

        foreach (var model in models) {
            builder.AppendLine(
                $"        services.AddSingleton<IValidatorFor<{model.QualifiedTypeName}>>(" +
                $"{Qualified(model)}.Instance);");
        }

        builder.AppendLine();

        foreach (var model in models) {
            builder.AppendLine($"        services.AddValidationRunner<{model.QualifiedTypeName}>();");
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string EmitTable(IReadOnlyList<ValidatedTypeModel> models, string ns) {
        var builder = Header(ns);

        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using ValidationModules;");
        builder.AppendLine();
        if (ns.Length > 0) {
            builder.AppendLine($"namespace {ns};");
            builder.AppendLine();
        }

        builder.AppendLine("/// <summary>Every validator this assembly generated, ready for AddValidationModules.</summary>");
        builder.AppendLine("public static class GeneratedValidators {");
        builder.AppendLine("    public static IReadOnlyList<ValidatorRegistration> All { get; } = new ValidatorRegistration[] {");

        foreach (var model in models) {
            // A factory delegate rather than a (service, implementation) pair, so nothing routes
            // through ActivatorUtilities constructor reflection.
            builder.AppendLine(
                $"        new ValidatorRegistration(typeof(IValidatorFor<{model.QualifiedTypeName}>), " +
                $"static _ => {Qualified(model)}.Instance),");
        }

        builder.AppendLine("    };");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static string Qualified(ValidatedTypeModel model) =>
        model.Namespace.Length == 0
            ? $"global::{model.ValidatorName}"
            : $"global::{model.Namespace}.{model.ValidatorName}";

    private static StringBuilder Header(string ns) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        return builder;
    }
}
