using System.Text;
using ValidationModules.SourceGenerator.Impl.Models;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// Turns a <see cref="ValidatedTypeModel"/> into a validator: one class, one method, straight-line
/// code, no rule graph to walk and nothing built per call.
/// </summary>
/// <remarks>
/// <para>
/// Every front-end feeds this, so a rule's origin cannot change the code that comes out.
/// </para>
/// <para>
/// Messages are composed by the runtime through the <c>ctx.Add*</c> helpers rather than emitted as
/// literals here. That is worth 107 of the 313 native bytes a constraint site would otherwise cost,
/// because every message embeds its field name and so nothing deduplicates in the string heap. A
/// constraint carrying an explicit message is the exception and emits a literal <c>ctx.Add</c>.
/// </para>
/// </remarks>
public sealed class ValidatorEmitter {

    public string Emit(ValidatedTypeModel model) {
        var builder = new StringBuilder();
        var patterns = new List<(string Field, ConstraintModel Constraint)>();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Text.RegularExpressions;");
        builder.AppendLine("using ValidationModules;");
        builder.AppendLine();
        if (model.Namespace.Length > 0) {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }
        builder.AppendLine($"public sealed partial class {model.ValidatorName} : IValidatorFor<{model.QualifiedTypeName}> {{");
        builder.AppendLine($"    public static readonly {model.ValidatorName} Instance = new();");
        builder.AppendLine();
        builder.AppendLine($"    private {model.ValidatorName}() {{ }}");
        builder.AppendLine();

        var body = new StringBuilder();
        foreach (var property in model.Properties) {
            EmitProperty(body, property, model, patterns);
        }

        foreach (var (field, constraint) in patterns) {
            var expression = constraint.Anchored
                ? $@"\A(?:{constraint.Pattern})\z"
                : constraint.Pattern!;

            // A static readonly Regex, not [GeneratedRegex]. Plan §2 mandates the latter and it is
            // unavailable here, for a narrower reason than it first appears. Post-initialization
            // output IS visible to other generators, so a [GeneratedRegex] emitted that way would be
            // implemented; output from RegisterSourceOutput is not, and fails with CS8795. Both
            // verified. Post-initialization cannot help: it runs before anything has been examined
            // and can read neither the compilation nor additional files, while a pattern is always
            // user data. See API-SURFACE.md §13.6.
            //
            // What §2 was actually protecting against is intact. The instance is built once at type
            // initialization rather than per validation call, and RegexOptions.Compiled is never
            // passed, so nothing goes through Reflection.Emit and the result stays AOT-clean. The
            // cost is an interpreted match rather than a source-generated one.
            // The options argument is omitted entirely when there is nothing to say, rather than
            // passed as RegexOptions.None. It is not cosmetic: the single-argument constructor lets
            // ILC prove RegexOptions.Compiled is never set and trim the RegexCompiler path with it,
            // and passing the enum defeats that. Measured at 713 KB on a published AOT binary -
            // more than the regex engine itself costs.
            var options = constraint.RegexOptions != 0
                ? $", (RegexOptions){constraint.RegexOptions}"
                : string.Empty;

            builder.AppendLine(
                $"    private static readonly Regex {field} = new Regex({Quote(expression)}{options});");
            builder.AppendLine();
        }

        builder.AppendLine($"    public void Validate(ref ValidationContext ctx, {model.QualifiedTypeName} value) {{");
        builder.Append(body);
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void EmitProperty(
        StringBuilder builder,
        ValidatedPropertyModel property,
        ValidatedTypeModel model,
        List<(string, ConstraintModel)> patterns) {

        var access = $"value.{property.PropertyName}";
        var field = Quote(property.FieldName);
        var required = property.Constraints.FirstOrDefault(c => c.Kind == ConstraintKind.Required);
        var wroteChain = false;

        if (required is not null) {
            builder.AppendLine($"        if ({RequiredTest(access, property, required)}) {Add(field, required, "AddRequired", "")}");
            wroteChain = true;
        }

        foreach (var constraint in property.Constraints) {
            if (constraint.Kind == ConstraintKind.Required) {
                continue;
            }

            var test = TestFor(access, property, constraint, model, patterns);
            if (test is null) {
                continue;
            }

            // else-if after a required check is an optimization, not the suppression mechanism -
            // the collector drops anything on a field that already failed required. It still earns
            // its place by not evaluating a length or pattern test against a value known to be null.
            var keyword = wroteChain ? "        else if" : "        if";
            builder.AppendLine($"{keyword} ({test}) {AddFor(field, constraint, property)}");
            wroteChain = true;
        }

        EmitNested(builder, property, access);
    }

    private static void EmitNested(StringBuilder builder, ValidatedPropertyModel property, string access) {
        if (property.ElementValidatorName is null) {
            return;
        }

        if (property.Shape == PropertyShape.Dictionary) {
            var entries = $"entries{property.PropertyName}";

            builder.AppendLine($"        if ({access} is {{ }} {entries}) {{");
            builder.AppendLine($"            foreach (var pair in {entries}) {{");
            builder.AppendLine("                if (pair.Value is not null) {");
            builder.AppendLine($"                    var entryCtx = ctx.PushKey({Quote(property.FieldName)}, pair.Key?.ToString() ?? \"\");");
            builder.AppendLine($"                    {property.ElementValidatorName}.Instance.Validate(ref entryCtx, pair.Value);");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine("        }");
            return;
        }

        if (property.Shape == PropertyShape.Object) {
            builder.AppendLine($"        if ({access} is {{ }} nested{property.PropertyName}) {{");
            builder.AppendLine($"            var ctx{property.PropertyName} = ctx.Push({Quote(property.FieldName)});");
            builder.AppendLine($"            {property.ElementValidatorName}.Instance.Validate(ref ctx{property.PropertyName}, nested{property.PropertyName});");
            builder.AppendLine("        }");
            return;
        }

        var items = $"items{property.PropertyName}";
        var index = $"i{property.PropertyName}";

        builder.AppendLine($"        if ({access} is {{ }} {items}) {{");

        if (property.IsIndexable) {
            // A for loop rather than foreach: enumerating an interface-typed collection boxes the
            // struct enumerator, and a clean pass over a collection property would then allocate.
            builder.AppendLine($"            for (var {index} = 0; {index} < {items}.{property.CountAccessor}; {index}++) {{");
            builder.AppendLine($"                var element = {items}[{index}];");
        } else {
            builder.AppendLine($"            var {index} = 0;");
            builder.AppendLine($"            foreach (var element in {items}) {{");
        }

        builder.AppendLine("                if (element is not null) {");
        builder.AppendLine($"                    var elementCtx = ctx.PushIndex({Quote(property.FieldName)}, {index});");
        builder.AppendLine($"                    {property.ElementValidatorName}.Instance.Validate(ref elementCtx, element);");
        builder.AppendLine("                }");

        if (!property.IsIndexable) {
            builder.AppendLine($"                {index}++;");
        }

        builder.AppendLine("            }");
        builder.AppendLine("        }");
    }

    private static string RequiredTest(string access, ValidatedPropertyModel property, ConstraintModel constraint) {
        if (property.IsString) {
            return constraint.AllowEmptyStrings
                ? $"{access} is null"
                : $"string.IsNullOrWhiteSpace({access})";
        }

        return property.IsNullableValueType ? $"{access} is null" : $"{access} is null";
    }

    private static string? TestFor(
        string access,
        ValidatedPropertyModel property,
        ConstraintModel constraint,
        ValidatedTypeModel model,
        List<(string, ConstraintModel)> patterns) {

        var value = property.IsNullableValueType ? $"{access}.Value" : access;
        var guard = property.IsReferenceType || property.IsNullableValueType ? $"{access} is not null && " : string.Empty;

        switch (constraint.Kind) {
            case ConstraintKind.StringLength: {
                var tests = new List<string>();
                if (constraint.Min is { } min && min != "0") {
                    tests.Add($"{access}.Length < {min}");
                }

                if (constraint.Max is { } max && max != int.MaxValue.ToString()) {
                    tests.Add($"{access}.Length > {max}");
                }

                return tests.Count == 0 ? null : $"{guard}({string.Join(" || ", tests)})";
            }

            case ConstraintKind.ItemCount: {
                var tests = new List<string>();
                if (constraint.Min is { } min && min != "0") {
                    tests.Add($"{access}.{property.CountAccessor} < {min}");
                }

                if (constraint.Max is { } max && max != int.MaxValue.ToString()) {
                    tests.Add($"{access}.{property.CountAccessor} > {max}");
                }

                return tests.Count == 0 ? null : $"{guard}({string.Join(" || ", tests)})";
            }

            case ConstraintKind.Range: {
                var low = constraint.ExclusiveMin ? "<=" : "<";
                var high = constraint.ExclusiveMax ? ">=" : ">";
                return $"{guard}({value} {low} {constraint.Min} || {value} {high} {constraint.Max})";
            }

            case ConstraintKind.Pattern: {
                // The reference form resolves to the consumer's own [GeneratedRegex], so nothing is
                // declared here and the regex engine is never rooted.
                if (constraint.RegexAccessor is { } accessor) {
                    return $"{guard}!{accessor}.IsMatch({access})";
                }

                var field = $"{property.PropertyName}Pattern{patterns.Count}";
                patterns.Add((field, constraint));
                return $"{guard}!{field}.IsMatch({access})";
            }

            case ConstraintKind.AllowedValues: {
                if (constraint.Values.Count == 0) {
                    return null;
                }

                var comparisons = string.Join(" && ", constraint.Values.Select(v => $"{value} != {v}"));
                var anyMatch = string.Join(" || ", constraint.Values.Select(v => $"{value} == {v}"));
                return constraint.Negated ? $"{guard}({anyMatch})" : $"{guard}({comparisons})";
            }

            default:
                return null;
        }
    }

    private static string AddFor(string field, ConstraintModel constraint, ValidatedPropertyModel property) =>
        constraint.Kind switch {
            ConstraintKind.StringLength => Add(field, constraint, "AddStringLength", Bounds(constraint)),
            ConstraintKind.ItemCount => Add(field, constraint, "AddItemCount", Bounds(constraint)),
            ConstraintKind.Range => Add(field, constraint, "AddRange", $", {constraint.Min}, {constraint.Max}"),
            ConstraintKind.Pattern => Add(field, constraint, "AddPattern", ""),
            ConstraintKind.AllowedValues => Add(field, constraint, "AddAllowedValues",
                $", {Quote(string.Join(", ", constraint.Values.Select(Unquote)))}"),
            _ => Add(field, constraint, "AddRequired", ""),
        };

    private static string Bounds(ConstraintModel constraint) =>
        $", {constraint.Min ?? "0"}, {constraint.Max ?? int.MaxValue.ToString()}";

    /// <summary>
    /// A constraint carrying an explicit message falls back to the literal overload: at that point
    /// the text is one the author chose rather than one the runtime owns.
    /// </summary>
    private static string Add(string field, ConstraintModel constraint, string helper, string arguments) {
        if (constraint.Message is { } message) {
            var code = constraint.Code is { } custom ? Quote(custom) : CodeConstant(constraint.Kind);
            return $"ctx.Add({field}, {code}, {Quote(message)});";
        }

        return $"ctx.{helper}({field}{arguments});";
    }

    private static string CodeConstant(ConstraintKind kind) => kind switch {
        ConstraintKind.Required => "ValidationCodes.Required",
        ConstraintKind.StringLength => "ValidationCodes.StringLength",
        ConstraintKind.Range => "ValidationCodes.Range",
        ConstraintKind.Pattern => "ValidationCodes.Pattern",
        ConstraintKind.AllowedValues => "ValidationCodes.Enum",
        _ => "ValidationCodes.ArrayBounds",
    };

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Unquote(string literal) =>
        literal.Length >= 2 && literal[0] == '"' ? literal.Substring(1, literal.Length - 2) : literal;
}
