using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using ValidationModules.SourceGenerator.Impl.Models;

namespace ValidationModules.SourceGenerator.Impl.Emitters;

/// <summary>
/// Turns a <see cref="ValidatedTypeModel"/> into a validator: one class, one method, straight-line
/// code, no rule graph to walk and nothing built per call.
/// </summary>
/// <remarks>
/// <para>
/// Every front-end feeds this, so a rule's origin cannot change the code that comes out.
/// </para>
/// <para>
/// Messages are composed by the runtime through the <c>ctx.Add*</c> helpers rather than emitted as
/// literals here. That is worth 107 of the 313 native bytes a constraint site would otherwise cost,
/// because every message embeds its field name and so nothing deduplicates in the string heap. A
/// constraint carrying an explicit message is the exception and emits a literal <c>ctx.Add</c>.
/// </para>
/// </remarks>
public sealed class ValidatorEmitter {

    public string Emit(ValidatedTypeModel model) {
        var builder = new StringBuilder();
        var patterns = new List<(string Field, ConstraintModel Constraint)>();

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using System.Text.RegularExpressions;");
        builder.AppendLine("using ValidationModules;");
        builder.AppendLine();
        if (model.Namespace.Length > 0) {
            builder.AppendLine($"namespace {model.Namespace};");
            builder.AppendLine();
        }
        // internal for an internal model: a public class cannot take a less accessible type as a
        // method parameter (CS0051), and the error would land inside generated code.
        var accessibility = model.IsPublic ? "public" : "internal";

        builder.AppendLine($"{accessibility} sealed partial class {model.ValidatorName} : IValidatorFor<{model.QualifiedTypeName}> {{");
        builder.AppendLine();
        EmitNestedDependencies(builder, model);

        var body = new StringBuilder();
        var fast = new StringBuilder();

        foreach (var property in model.Properties) {
            EmitProperty(body, fast, property, model, patterns);
        }

        // Applied rules own no property, so they run once every property has been walked. Ordering
        // them last rather than at their declaration point is §19.7: they are the only rules whose
        // position in the body says nothing about which field they concern.
        foreach (var rule in model.AppliedRules) {
            body.AppendLine($"        {rule}(ref ctx, value);");
        }

        foreach (var (field, constraint) in patterns) {
            var expression = constraint.Anchored
                ? $@"\A(?:{constraint.Pattern})\z"
                : constraint.Pattern!;

            // A static readonly Regex, not [GeneratedRegex]. Plan §2 mandates the latter and it is
            // unavailable here, for a narrower reason than it first appears. Post-initialization
            // output IS visible to other generators, so a [GeneratedRegex] emitted that way would be
            // implemented; output from RegisterSourceOutput is not, and fails with CS8795. Both
            // verified. Post-initialization cannot help: it runs before anything has been examined
            // and can read neither the compilation nor additional files, while a pattern is always
            // user data. See API-SURFACE.md §13.6.
            //
            // What §2 was actually protecting against is intact. The instance is built once at type
            // initialization rather than per validation call, and RegexOptions.Compiled is never
            // passed, so nothing goes through Reflection.Emit and the result stays AOT-clean. The
            // cost is an interpreted match rather than a source-generated one.
            // The options argument is omitted entirely when there is nothing to say, rather than
            // passed as RegexOptions.None. It is not cosmetic: the single-argument constructor lets
            // ILC prove RegexOptions.Compiled is never set and trim the RegexCompiler path with it,
            // and passing the enum defeats that. Measured at 713 KB on a published AOT binary -
            // more than the regex engine itself costs.
            var options = constraint.RegexOptions != 0
                ? $", (RegexOptions){constraint.RegexOptions}"
                : string.Empty;

            builder.AppendLine(
                $"    private static readonly Regex {field} = new Regex({Quote(expression)}{options});");
            builder.AppendLine();
        }

        builder.AppendLine($"    public void Validate(ref ValidationContext ctx, {model.QualifiedTypeName} value) {{");
        builder.Append(body);
        builder.AppendLine("    }");

        // An applied rule is handed the context and owns what it records, so there is no condition
        // to test without one. A type carrying any falls back to IValidatorFor<T>.IsValid, which
        // walks properly - correct, just not free.
        if (model.AppliedRules.Count == 0) {
            builder.AppendLine();
            builder.AppendLine("    /// <summary>");
            builder.AppendLine("    /// The same tests as <see cref=\"Validate\"/>, returning at the first failure and building");
            builder.AppendLine("    /// no path, message or error record - a caller wanting only a boolean pays for nothing else.");
            builder.AppendLine("    /// </summary>");
            builder.AppendLine($"    public bool IsValid({model.QualifiedTypeName} value) {{");
            builder.Append(fast);
            builder.AppendLine("        return true;");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// The constructor pair, and the fields holding whatever validates each nested property.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Nested validators are injected, not reached statically.</b> The container owns the graph,
    /// so registering a second <c>IValidatorFor&lt;Address&gt;</c> composes with the generated one
    /// wherever an Address is reached - as a property of a Pet exactly as much as on its own. The
    /// set is resolved once when the singleton is built rather than per descent.
    /// </para>
    /// <para>
    /// <b>Held as arrays rather than as the injected IEnumerable.</b> Enumerating an
    /// interface-typed sequence boxes the enumerator, which would allocate on a clean pass at every
    /// nested property - the one thing the runtime promises it does not do. Materialised once in
    /// the constructor and walked with a for loop.
    /// </para>
    /// <para>
    /// <b>The parameterless constructor fills in lazily, and that is not a micro-optimization.</b>
    /// Building the defaults eagerly would recurse forever on a self-referential model - a Node
    /// whose Child is a Node constructs a NodeValidator whose constructor constructs a
    /// NodeValidator - and a StackOverflowException cannot be caught. Demand-driven initialisation
    /// terminates because nothing is built until a value actually descends, at which point the
    /// depth guard bounds it. The race on first use is benign: two threads build equivalent arrays
    /// and one wins.
    /// </para>
    /// </remarks>
    private static void EmitNestedDependencies(StringBuilder builder, ValidatedTypeModel model) {
        var nested = model.Properties.Where(p => p.ElementValidatorName is not null).ToList();

        if (nested.Count == 0) {
            builder.AppendLine($"    public {model.ValidatorName}() {{ }}");
            builder.AppendLine();
            return;
        }

        foreach (var property in nested) {
            builder.AppendLine(
                $"    private IValidatorFor<{ElementType(property)}>[]? {Field(property)};");
        }

        builder.AppendLine();
        builder.AppendLine("    /// <summary>Resolved from the container: the full set for each nested type.</summary>");
        builder.AppendLine($"    public {model.ValidatorName}(");

        for (var i = 0; i < nested.Count; i++) {
            var comma = i == nested.Count - 1 ? ") {" : ",";
            builder.AppendLine(
                $"        System.Collections.Generic.IEnumerable<IValidatorFor<{ElementType(nested[i])}>> {Parameter(nested[i])}{comma}");
        }

        foreach (var property in nested) {
            builder.AppendLine(
                $"        {Field(property)} = System.Linq.Enumerable.ToArray({Parameter(property)});");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Standalone: nested types fall back to their own generated validators.</summary>");
        builder.AppendLine($"    public {model.ValidatorName}() {{ }}");
        builder.AppendLine();

        foreach (var property in nested) {
            // A property that nests its own type resolves to this instance rather than a new one,
            // which is both correct and the cheapest way to terminate the common cycle.
            var fallback = property.ElementValidatorName == $"global::{Qualify(model)}"
                ? "this"
                : $"new {property.ElementValidatorName}()";

            builder.AppendLine(
                $"    private IValidatorFor<{ElementType(property)}>[] {Accessor(property)} =>");
            builder.AppendLine(
                $"        {Field(property)} ??= new IValidatorFor<{ElementType(property)}>[] {{ {fallback} }};");
            builder.AppendLine();
        }
    }

    /// <summary>
    /// The type a nested property's validators are for. A collection or dictionary carries its
    /// element type; a plain object's element type is the property's own, which the front end
    /// leaves null because nothing needed it before now.
    /// </summary>
    private static string ElementType(ValidatedPropertyModel property) =>
        property.ElementTypeName ?? property.TypeName;

    private static string Field(ValidatedPropertyModel property) => $"_{Camel(property.PropertyName)}Validators";

    /// <summary>
    /// The constructor parameter carrying this property's nested validators.
    /// </summary>
    /// <remarks>
    /// Escaped, and this is the case that does not need a verbatim identifier anywhere in the
    /// consumer's source to reach: the parameter is the property name camel-cased, so an ordinary
    /// <c>Object</c>, <c>Event</c> or <c>Default</c> property lands on <c>object</c>, <c>event</c>
    /// or <c>default</c>. <see cref="Field"/> and <see cref="Accessor"/> need no escape because
    /// both wrap the name in affixes, and no keyword survives having <c>_</c> or <c>Validators</c>
    /// stuck to it.
    /// </remarks>
    private static string Parameter(ValidatedPropertyModel property) => Escape(Camel(property.PropertyName));

    private static string Accessor(ValidatedPropertyModel property) => $"{property.PropertyName}Validators";

    private static string Camel(string name) =>
        name.Length == 0 || char.IsLower(name[0]) ? name : char.ToLowerInvariant(name[0]) + name.Substring(1);

    /// <summary>
    /// An identifier as it has to be written to be parsed back as one.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A property declared <c>@object</c> has the CLR name <c>object</c>: the <c>@</c> is C# syntax
    /// meaning "read this as an identifier", not part of the name, so the model does not carry it
    /// and the emitter has to put it back. <b>Only where the name is emitted as code.</b> The same
    /// name also reaches the wire as a string literal, where an <c>@</c> would corrupt every
    /// payload the property appears in, and reaches composite identifiers like
    /// <c>nestedHome</c>, where it would not parse at all. That is why this is applied at the two
    /// use sites rather than folded into the model.
    /// </para>
    /// <para>
    /// Reserved keywords only. <c>value</c>, <c>record</c> and <c>var</c> are contextual and are
    /// legal identifiers as they stand - <see cref="SyntaxFacts.GetKeywordKind"/> returns
    /// <see cref="SyntaxKind.None"/> for them, which is the distinction being relied on.
    /// </para>
    /// </remarks>
    private static string Escape(string identifier) =>
        SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;

    private static string Qualify(ValidatedTypeModel model) =>
        model.Namespace.Length == 0 ? model.ValidatorName : $"{model.Namespace}.{model.ValidatorName}";

    private static void EmitProperty(
        StringBuilder builder,
        StringBuilder fast,
        ValidatedPropertyModel property,
        ValidatedTypeModel model,
        List<(string, ConstraintModel)> patterns) {

        var access = $"value.{Escape(property.PropertyName)}";
        var field = Quote(property.FieldName);
        var required = property.Constraints.FirstOrDefault(c => c.Kind == ConstraintKind.Required);
        var wroteChain = false;

        if (required is not null) {
            var requiredTest = RequiredTest(access, property, required);

            builder.AppendLine($"        if ({requiredTest}) {Add(field, required, "AddRequired", "")}");
            fast.AppendLine($"        if ({requiredTest}) return false;");
            wroteChain = true;
        }

        foreach (var constraint in property.Constraints) {
            if (constraint.Kind == ConstraintKind.Required) {
                continue;
            }

            var test = TestFor(access, property, constraint, model, patterns);
            if (test is null) {
                continue;
            }

            // else-if after a required check is an optimization, not the suppression mechanism -
            // the collector drops anything on a field that already failed required. It still earns
            // its place by not evaluating a length or pattern test against a value known to be null.
            //
            // A predicate stays out of the chain, in both directions. It may read fields other than
            // the one it is anchored to, so an earlier failure on the anchor says nothing about
            // whether it would fail; and skipping it would make this engine report fewer errors than
            // the runtime one, which walks every rule. §4.2 allows exactly one short-circuit and this
            // is not it.
            var standalone = constraint.Kind == ConstraintKind.Predicate;
            var keyword = wroteChain && !standalone ? "        else if" : "        if";
            builder.AppendLine($"{keyword} ({test}) {AddFor(field, constraint, property)}");

            // No else-if here: a failure has already returned, so the next test is only reached
            // when the previous one passed. The chain in Validate exists to avoid evaluating a
            // length test against a value known to be null; returning gets that for free.
            fast.AppendLine($"        if ({test}) return false;");

            // A standalone predicate also ends the chain, rather than merely not joining it: a
            // following `else if` would otherwise bind to the predicate's `if` and be skipped
            // whenever the predicate failed.
            wroteChain = !standalone;
        }

        EmitNested(builder, fast, property, access);
    }

    private static void EmitNested(
        StringBuilder builder,
        StringBuilder fast,
        ValidatedPropertyModel property,
        string access) {
        if (property.ElementValidatorName is null) {
            return;
        }

        if (property.Shape == PropertyShape.Dictionary) {
            var entries = $"entries{property.PropertyName}";

            builder.AppendLine($"        if ({access} is {{ }} {entries}) {{");
            builder.AppendLine($"            foreach (var pair in {entries}) {{");
            builder.AppendLine("                if (pair.Value is not null) {");
            builder.AppendLine($"                    var entryCtx = ctx.PushKey({Quote(property.FieldName)}, pair.Key?.ToString() ?? \"\");");
            builder.AppendLine($"                    var entryValidators = {Accessor(property)};");
            builder.AppendLine("                    for (var vi = 0; vi < entryValidators.Length; vi++) {");
            builder.AppendLine("                        entryValidators[vi].Validate(ref entryCtx, pair.Value);");
            builder.AppendLine("                    }");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
            builder.AppendLine("        }");

            fast.AppendLine($"        if ({access} is {{ }} {entries}) {{");
            fast.AppendLine($"            foreach (var pair in {entries}) {{");
            fast.AppendLine("                if (pair.Value is not null) {");
            fast.AppendLine($"                    var entryValidators = {Accessor(property)};");
            fast.AppendLine("                    for (var vi = 0; vi < entryValidators.Length; vi++) {");
            fast.AppendLine("                        if (!entryValidators[vi].IsValid(pair.Value)) return false;");
            fast.AppendLine("                    }");
            fast.AppendLine("                }");
            fast.AppendLine("            }");
            fast.AppendLine("        }");
            return;
        }

        if (property.Shape == PropertyShape.Object) {
            builder.AppendLine($"        if ({access} is {{ }} nested{property.PropertyName}) {{");
            builder.AppendLine($"            var ctx{property.PropertyName} = ctx.Push({Quote(property.FieldName)});");
            builder.AppendLine($"            var validators{property.PropertyName} = {Accessor(property)};");
            builder.AppendLine($"            for (var vi = 0; vi < validators{property.PropertyName}.Length; vi++) {{");
            builder.AppendLine($"                validators{property.PropertyName}[vi].Validate(ref ctx{property.PropertyName}, nested{property.PropertyName});");
            builder.AppendLine("            }");
            builder.AppendLine("        }");

            fast.AppendLine($"        if ({access} is {{ }} nested{property.PropertyName}) {{");
            fast.AppendLine($"            var validators{property.PropertyName} = {Accessor(property)};");
            fast.AppendLine($"            for (var vi = 0; vi < validators{property.PropertyName}.Length; vi++) {{");
            fast.AppendLine($"                if (!validators{property.PropertyName}[vi].IsValid(nested{property.PropertyName})) return false;");
            fast.AppendLine("            }");
            fast.AppendLine("        }");
            return;
        }

        var items = $"items{property.PropertyName}";
        var index = $"i{property.PropertyName}";

        builder.AppendLine($"        if ({access} is {{ }} {items}) {{");

        if (property.IsIndexable) {
            // A for loop rather than foreach: enumerating an interface-typed collection boxes the
            // struct enumerator, and a clean pass over a collection property would then allocate.
            builder.AppendLine($"            for (var {index} = 0; {index} < {items}.{property.CountAccessor}; {index}++) {{");
            builder.AppendLine($"                var element = {items}[{index}];");
        } else {
            builder.AppendLine($"            var {index} = 0;");
            builder.AppendLine($"            foreach (var element in {items}) {{");
        }

        builder.AppendLine("                if (element is not null) {");
        builder.AppendLine($"                    var elementCtx = ctx.PushIndex({Quote(property.FieldName)}, {index});");
        builder.AppendLine($"                    var elementValidators = {Accessor(property)};");
        builder.AppendLine("                    for (var vi = 0; vi < elementValidators.Length; vi++) {");
        builder.AppendLine("                        elementValidators[vi].Validate(ref elementCtx, element);");
        builder.AppendLine("                    }");
        builder.AppendLine("                }");

        if (!property.IsIndexable) {
            builder.AppendLine($"                {index}++;");
        }

        builder.AppendLine("            }");
        builder.AppendLine("        }");

        fast.AppendLine($"        if ({access} is {{ }} {items}) {{");

        if (property.IsIndexable) {
            fast.AppendLine($"            for (var {index} = 0; {index} < {items}.{property.CountAccessor}; {index}++) {{");
            fast.AppendLine($"                var element = {items}[{index}];");
        } else {
            fast.AppendLine($"            foreach (var element in {items}) {{");
        }

        fast.AppendLine("                if (element is not null) {");
        fast.AppendLine($"                    var elementValidators = {Accessor(property)};");
        fast.AppendLine("                    for (var vi = 0; vi < elementValidators.Length; vi++) {");
        fast.AppendLine("                        if (!elementValidators[vi].IsValid(element)) return false;");
        fast.AppendLine("                    }");
        fast.AppendLine("                }");
        fast.AppendLine("            }");
        fast.AppendLine("        }");
    }

    private static string RequiredTest(string access, ValidatedPropertyModel property, ConstraintModel constraint) {
        if (property.IsString) {
            return constraint.AllowEmptyStrings
                ? $"{access} is null"
                : $"string.IsNullOrWhiteSpace({access})";
        }

        return property.IsNullableValueType ? $"{access} is null" : $"{access} is null";
    }

    private static string? TestFor(
        string access,
        ValidatedPropertyModel property,
        ConstraintModel constraint,
        ValidatedTypeModel model,
        List<(string, ConstraintModel)> patterns) {

        var value = property.IsNullableValueType ? $"{access}.Value" : access;
        var guard = property.IsReferenceType || property.IsNullableValueType ? $"{access} is not null && " : string.Empty;

        switch (constraint.Kind) {
            // No null guard, deliberately. A predicate may read fields other than the one it is
            // anchored to - "x => x.Start < x.End" is pathed at start and reads both - so guarding on
            // the anchor would skip a rule that had nothing to do with it. Null is the author's, the
            // same as it is on the runtime path.
            case ConstraintKind.Predicate:
                return constraint.PredicateAccessor is { } predicate ? $"!{predicate}(value)" : null;

            case ConstraintKind.StringLength: {
                var tests = new List<string>();
                if (constraint.Min is { } min && min != "0") {
                    tests.Add($"{access}.Length < {min}");
                }

                if (constraint.Max is { } max && max != int.MaxValue.ToString()) {
                    tests.Add($"{access}.Length > {max}");
                }

                return tests.Count == 0 ? null : $"{guard}({string.Join(" || ", tests)})";
            }

            case ConstraintKind.ItemCount: {
                var tests = new List<string>();
                if (constraint.Min is { } min && min != "0") {
                    tests.Add($"{access}.{property.CountAccessor} < {min}");
                }

                if (constraint.Max is { } max && max != int.MaxValue.ToString()) {
                    tests.Add($"{access}.{property.CountAccessor} > {max}");
                }

                return tests.Count == 0 ? null : $"{guard}({string.Join(" || ", tests)})";
            }

            // Each bound is optional and an absent one emits nothing, so a spec that set only
            // `minimum` compiles to one comparison rather than two, the second of which could never
            // fail and whose bound the composed message would then quote back at the caller.
            case ConstraintKind.Range: {
                var tests = new List<string>();
                if (constraint.Min is { } min) {
                    tests.Add($"{value} {(constraint.ExclusiveMin ? "<=" : "<")} {min}");
                }

                if (constraint.Max is { } max) {
                    tests.Add($"{value} {(constraint.ExclusiveMax ? ">=" : ">")} {max}");
                }

                return tests.Count == 0 ? null : $"{guard}({string.Join(" || ", tests)})";
            }

            // An integral or decimal member divides exactly, so it keeps the straight-line form the
            // rest of this switch has. A double or float cannot: `0.3 % 0.01` is 0.00999999999999998
            // in binary floating point, so the check goes through the runtime, which converts to
            // decimal first. The divisor already arrives in the right denomination.
            case ConstraintKind.MultipleOf: {
                if (constraint.Divisor is not { } divisor) {
                    return null;
                }

                return constraint.DecimalDomain
                    ? $"{guard}!global::ValidationModules.ConstraintChecks.IsMultipleOf({value}, {divisor})"
                    : $"{guard}({value} % {divisor} != 0)";
            }

            // The only constraint here that is not a comparison. Typed on IEnumerable<T>, so a
            // property with no Count needs no separate path - the fallback the count constraints
            // have does not arise.
            case ConstraintKind.UniqueItems:
                return $"{guard}!global::ValidationModules.ConstraintChecks.AllUnique({access})";

            case ConstraintKind.Pattern: {
                // The reference form resolves to the consumer's own [GeneratedRegex], so nothing is
                // declared here and the regex engine is never rooted.
                if (constraint.RegexAccessor is { } accessor) {
                    return $"{guard}!{accessor}.IsMatch({access})";
                }

                var field = $"{property.PropertyName}Pattern{patterns.Count}";
                patterns.Add((field, constraint));
                return $"{guard}!{field}.IsMatch({access})";
            }

            case ConstraintKind.AllowedValues: {
                if (constraint.Values.Count == 0) {
                    return null;
                }

                var comparisons = string.Join(" && ", constraint.Values.Select(v => $"{value} != {v}"));
                var anyMatch = string.Join(" || ", constraint.Values.Select(v => $"{value} == {v}"));
                return constraint.Negated ? $"{guard}({anyMatch})" : $"{guard}({comparisons})";
            }

            default:
                return null;
        }
    }

    private static string AddFor(string field, ConstraintModel constraint, ValidatedPropertyModel property) =>
        constraint.Kind switch {
            ConstraintKind.StringLength => Add(field, constraint, "AddStringLength", Bounds(constraint)),
            ConstraintKind.ItemCount => Add(field, constraint, "AddItemCount", Bounds(constraint)),
            ConstraintKind.Range => RangeAdd(field, constraint),
            ConstraintKind.MultipleOf => Add(field, constraint, "AddMultipleOf", $", {constraint.Divisor}"),
            ConstraintKind.UniqueItems => Add(field, constraint, "AddUniqueItems", ""),
            ConstraintKind.Pattern => Add(field, constraint, "AddPattern", ""),
            ConstraintKind.AllowedValues => Add(field, constraint, "AddAllowedValues",
                $", {Quote(string.Join(", ", Displays(constraint)))}"),

            // Always the literal branch: a predicate's message was rendered from its own source when
            // the front-end read it, so there is nothing here to compose and nothing the runtime
            // could compose it from.
            ConstraintKind.Predicate => Add(field, constraint, "Add", ""),
            _ => Add(field, constraint, "AddRequired", ""),
        };

    /// <summary>
    /// The report call for a range, which has a different message per shape rather than one message
    /// with a bound the author never wrote standing in for the missing side.
    /// </summary>
    private static string RangeAdd(string field, ConstraintModel constraint) => constraint switch {
        { Min: { } min, Max: { } max } => Add(field, constraint, "AddRange", $", {min}, {max}"),
        { Min: { } min } => Add(field, constraint, "AddRangeAtLeast", $", {min}"),
        { Max: { } max } => Add(field, constraint, "AddRangeAtMost", $", {max}"),

        // Unreachable: a range with neither bound is VM0026 and never reaches the emitter.
        _ => Add(field, constraint, "AddRequired", ""),
    };

    private static string Bounds(ConstraintModel constraint) =>
        $", {constraint.Min ?? "0"}, {constraint.Max ?? int.MaxValue.ToString()}";

    /// <summary>
    /// A constraint carrying an explicit message falls back to the literal overload: at that point
    /// the text is one the author chose rather than one the runtime owns.
    /// </summary>
    private static string Add(string field, ConstraintModel constraint, string helper, string arguments) {
        if (constraint.Message is { } message) {
            var code = constraint.Code is { } custom ? Quote(custom) : CodeConstant(constraint.Kind);
            return $"ctx.Add({field}, {code}, {Quote(message)});";
        }

        return $"ctx.{helper}({field}{arguments});";
    }

    private static string CodeConstant(ConstraintKind kind) => kind switch {
        ConstraintKind.Required => "ValidationCodes.Required",
        ConstraintKind.StringLength => "ValidationCodes.StringLength",
        ConstraintKind.Range => "ValidationCodes.Range",
        ConstraintKind.Pattern => "ValidationCodes.Pattern",
        ConstraintKind.AllowedValues => "ValidationCodes.Enum",
        ConstraintKind.MultipleOf => "ValidationCodes.MultipleOf",
        ConstraintKind.UniqueItems => "ValidationCodes.UniqueItems",
        ConstraintKind.Predicate => "ValidationCodes.Predicate",
        _ => "ValidationCodes.ArrayBounds",
    };

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private static string Unquote(string literal) =>
        literal.Length >= 2 && literal[0] == '"' ? literal.Substring(1, literal.Length - 2) : literal;

    /// <summary>
    /// The permitted set as a reader should see it: <c>Pro, Enterprise</c> rather than
    /// <c>global::My.Tier.Pro, global::My.Tier.Enterprise</c>.
    /// </summary>
    /// <remarks>
    /// Falls back to unquoting the literals when a front end supplied no displays, which is every
    /// front end but the native one - their values are strings and numbers, where unquoting is the
    /// whole of the transform.
    /// </remarks>
    private static IEnumerable<string> Displays(ConstraintModel constraint) =>
        constraint.ValueDisplays.Count == constraint.Values.Count && constraint.Values.Count > 0
            ? constraint.ValueDisplays
            : constraint.Values.Select(Unquote);
}
