#:package CSharpier.Core@1.3.0
#:property NuGetAudit=false
#:property TreatWarningsAsErrors=false

// Formats the ```csharp fences in the Markdown, so a sample a reader copies is laid out the way
// the library's own source is.
//
//     dotnet run scripts/format-doc-snippets.cs            rewrite the fences
//     dotnet run scripts/format-doc-snippets.cs --check    report, and exit 1 if any would change
//
// CSharpier formats files, and a fence is not one. Two things follow. A fence that is a fragment -
// a property and its attribute, a method with no enclosing type - does not parse on its own, so it
// is retried inside a synthetic class and unwrapped afterwards. A fence that parses neither way is
// left alone: pages show deliberately-wrong code next to the diagnostic it raises, and elided
// bodies written with a literal ellipsis.
//
// A fence that reads as a table rather than as code opts out with a marker on the line above:
//
//     <!-- format:skip -->
//
// It is for a signature listing whose columns line up to be scanned down. CSharpier breaks every
// parameter list that crosses the print width onto its own lines, which is right for code and
// turns such a listing into something three times as long that nobody can scan. This is not a
// general escape hatch for disagreeing with the formatter.
//
// The package version here tracks the tool in .config/dotnet-tools.json. They format the same way
// only while they are the same version.

using System.Text;
using System.Text.RegularExpressions;
using CSharpier.Core.CSharp;

var check = args.Contains("--check");
var paths = args.Where(a => !a.StartsWith("--", StringComparison.Ordinal)).ToArray();
var root = FindRepositoryRoot();

var files = paths.Length > 0 ? paths.Select(Path.GetFullPath).ToArray() : DefaultFiles(root);

var fence = new Regex(
    @"(?m)^(?<skip><!--[ \t]*format:skip[ \t]*-->[ \t]*\r?\n)?"
        + @"```csharp[ \t]*\r?\n(?<code>.*?)\r?\n```[ \t]*$",
    RegexOptions.Singleline
);

var autoGeneratedHeader = new Regex(@"\A//[ \t]*<auto-?generated[^\n]*\r?\n");

var changed = new List<string>();
var skipped = 0;
var checkedCount = 0;

foreach (var file in files)
{
    var text = await File.ReadAllTextAsync(file);
    var rewritten = new StringBuilder();
    var last = 0;
    var fileChanged = false;

    foreach (Match match in fence.Matches(text))
    {
        if (match.Groups["skip"].Success)
        {
            skipped++;
            continue;
        }

        checkedCount++;

        var code = match.Groups["code"].Value;
        var formatted = await FormatSnippet(code);

        if (formatted is null)
        {
            skipped++;
            continue;
        }

        if (formatted == code)
        {
            continue;
        }

        if (!fileChanged)
        {
            changed.Add(Path.GetRelativePath(root, file));
            fileChanged = true;
        }

        rewritten.Append(text, last, match.Groups["code"].Index - last).Append(formatted);
        last = match.Groups["code"].Index + code.Length;
    }

    if (fileChanged && !check)
    {
        rewritten.Append(text, last, text.Length - last);
        await File.WriteAllTextAsync(file, rewritten.ToString());
    }
}

Console.WriteLine(
    $"{checkedCount} snippets, {changed.Count} file(s) "
        + $"{(check ? "would be" : "")} reformatted, {skipped} left as written."
);

if (changed.Count == 0)
{
    return 0;
}

foreach (var file in changed)
{
    Console.WriteLine($"  {file}");
}

if (!check)
{
    return 0;
}

Console.WriteLine();
Console.WriteLine("Run 'dotnet run scripts/format-doc-snippets.cs' to fix them.");

return 1;

// Returns the formatted snippet, or null when it parses neither bare nor wrapped.
async Task<string?> FormatSnippet(string code)
{
    // CSharpier returns a file starting with an auto-generated comment untouched, and says nothing
    // about it. Several pages open a sample with that comment to say the generator wrote it, and
    // the generator's real output is Allman, so the header is held back and put on afterwards.
    var header = autoGeneratedHeader.Match(code);

    if (header.Success)
    {
        var rest = await FormatSnippet(code[header.Length..]);

        return rest is null ? null : header.Value + rest;
    }

    var bare = await CSharpFormatter.FormatAsync(code);

    if (!bare.ErrorDiagnostics.Any())
    {
        return bare.Code.TrimEnd('\r', '\n');
    }

    var indented = string.Join(
        '\n',
        code.Split('\n').Select(line => line.Length == 0 ? line : "    " + line)
    );

    var wrapped = await CSharpFormatter.FormatAsync($"class Wrapper\n{{\n{indented}\n}}\n");

    if (wrapped.ErrorDiagnostics.Any())
    {
        return null;
    }

    var lines = wrapped.Code.TrimEnd('\r', '\n').Split('\n');

    // Drop "class Wrapper" and its two braces, then undo the indent that made it parse.
    return string.Join(
        '\n',
        lines[2..^1]
            .Select(line => line.StartsWith("    ", StringComparison.Ordinal) ? line[4..] : line)
    );
}

static string[] DefaultFiles(string root) =>
    [
        Path.Combine(root, "README.md"),
        .. Directory
            .EnumerateFiles(Path.Combine(root, "website"), "*.md", SearchOption.AllDirectories)
            .Where(f => !f.Contains("node_modules", StringComparison.Ordinal))
            .Order(StringComparer.Ordinal),
    ];

// A file-based app builds into a temp directory, so AppContext.BaseDirectory says nothing about
// where the repository is, and CallerFilePath is no better: a deterministic build rewrites it to
// /_/. Both callers run from the working tree, so walk up from there.
static string FindRepositoryRoot()
{
    var directory = new DirectoryInfo(Environment.CurrentDirectory);

    while (directory is not null && !Directory.Exists(Path.Combine(directory.FullName, ".git")))
    {
        directory = directory.Parent;
    }

    return directory?.FullName
        ?? throw new InvalidOperationException(
            $"No .git directory at or above {Environment.CurrentDirectory}."
        );
}
